// Auto-generated by scripts/bundle-schema.ts — do not edit

/** Valid job-level keywords from GitLab CI JSON Schema */
export const JOB_KEYWORDS: ReadonlySet<string> = new Set(["after_script","allow_failure","artifacts","before_script","cache","coverage","dependencies","environment","except","extends","hooks","id_tokens","identity","image","inherit","inputs","interruptible","manual_confirmation","needs","only","pages","parallel","publish","release","resource_group","retry","rules","run","script","secrets","services","stage","start_in","tags","timeout","trigger","variables","when"]);

/** Valid top-level keywords from GitLab CI JSON Schema */
export const TOP_LEVEL_KEYWORDS: ReadonlySet<string> = new Set(["after_script","before_script","cache","default","image","include","pages","services","spec","stages","variables","workflow"]);

/** Expected value types for job keywords (empty = any type allowed) */
export const JOB_KEYWORD_TYPES: Readonly<Record<string, { types: string[] }>> = {
  "image": {
    "types": [
      "string",
      "object"
    ]
  },
  "services": {
    "types": [
      "array"
    ]
  },
  "before_script": {
    "types": [
      "string",
      "array"
    ]
  },
  "after_script": {
    "types": [
      "string",
      "array"
    ]
  },
  "hooks": {
    "types": [
      "object"
    ]
  },
  "rules": {
    "types": [
      "array,null"
    ]
  },
  "variables": {
    "types": [
      "object"
    ]
  },
  "cache": {
    "types": [
      "array"
    ]
  },
  "id_tokens": {
    "types": [
      "object"
    ]
  },
  "identity": {
    "types": [
      "string"
    ]
  },
  "inputs": {
    "types": [
      "object"
    ]
  },
  "secrets": {
    "types": [
      "object"
    ]
  },
  "script": {
    "types": [
      "string",
      "array"
    ]
  },
  "run": {
    "types": [
      "array"
    ]
  },
  "stage": {
    "types": [
      "string",
      "array"
    ]
  },
  "only": {
    "types": [
      "null",
      "object"
    ]
  },
  "extends": {
    "types": [
      "string",
      "array"
    ]
  },
  "needs": {
    "types": [
      "array"
    ]
  },
  "except": {
    "types": [
      "null",
      "object"
    ]
  },
  "tags": {
    "types": [
      "array"
    ]
  },
  "allow_failure": {
    "types": [
      "boolean",
      "object"
    ]
  },
  "timeout": {
    "types": [
      "string"
    ]
  },
  "when": {
    "types": [
      "string"
    ]
  },
  "start_in": {
    "types": [
      "string"
    ]
  },
  "manual_confirmation": {
    "types": [
      "string"
    ]
  },
  "dependencies": {
    "types": [
      "array"
    ]
  },
  "artifacts": {
    "types": [
      "object,null"
    ]
  },
  "environment": {
    "types": [
      "string",
      "object"
    ]
  },
  "release": {
    "types": [
      "object"
    ]
  },
  "coverage": {
    "types": [
      "string"
    ]
  },
  "retry": {
    "types": [
      "object"
    ]
  },
  "parallel": {
    "types": [
      "integer",
      "object"
    ]
  },
  "interruptible": {
    "types": [
      "boolean"
    ]
  },
  "resource_group": {
    "types": [
      "string"
    ]
  },
  "trigger": {
    "types": [
      "object",
      "string"
    ]
  },
  "inherit": {
    "types": [
      "object"
    ]
  },
  "publish": {
    "types": [
      "string"
    ]
  },
  "pages": {
    "types": [
      "object",
      "boolean"
    ]
  }
};
