/**
 * Extract job-level and top-level keyword information from GitLab CI JSON Schema.
 * Generates src/data/bundled-schema.ts with keyword lists and type expectations.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SCHEMA_PATH = join(import.meta.dirname, '..', 'src', 'data', 'ci-schema.json');
const OUTPUT = join(import.meta.dirname, '..', 'src', 'data', 'bundled-schema.ts');

const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'));

// Extract job-level keywords from definitions.job_template.properties
const jobProps = schema.definitions?.job_template?.properties ?? {};
const jobKeywords = Object.keys(jobProps).sort();

// Extract expected types for job keywords
interface TypeInfo {
  types: string[];
}

function resolveTypes(prop: Record<string, unknown>): string[] {
  if (prop.type) {
    return [String(prop.type)];
  }
  if (prop.oneOf || prop.anyOf) {
    const variants = (prop.oneOf ?? prop.anyOf) as Record<string, unknown>[];
    const types = new Set<string>();
    for (const v of variants) {
      if (v.type) types.add(String(v.type));
    }
    return [...types];
  }
  if (prop.$ref) {
    const refName = String(prop.$ref).replace('#/definitions/', '');
    const refDef = schema.definitions?.[refName];
    if (refDef) return resolveTypes(refDef);
  }
  // Complex — allow any
  return [];
}

const jobKeywordTypes: Record<string, TypeInfo> = {};
for (const [key, value] of Object.entries(jobProps)) {
  const types = resolveTypes(value as Record<string, unknown>);
  if (types.length > 0) {
    jobKeywordTypes[key] = { types };
  }
}

// Extract top-level keywords
const topProps = schema.properties ?? {};
const topKeywords = Object.keys(topProps)
  .filter((k) => !k.startsWith('!') && !k.startsWith('$'))
  .sort();

const output = `// Auto-generated by scripts/bundle-schema.ts — do not edit

/** Valid job-level keywords from GitLab CI JSON Schema */
export const JOB_KEYWORDS: ReadonlySet<string> = new Set(${JSON.stringify(jobKeywords)});

/** Valid top-level keywords from GitLab CI JSON Schema */
export const TOP_LEVEL_KEYWORDS: ReadonlySet<string> = new Set(${JSON.stringify(topKeywords)});

/** Expected value types for job keywords (empty = any type allowed) */
export const JOB_KEYWORD_TYPES: Readonly<Record<string, { types: string[] }>> = ${JSON.stringify(jobKeywordTypes, null, 2)};
`;

writeFileSync(OUTPUT, output);
console.log(
  `Schema bundled → ${OUTPUT} (${jobKeywords.length} job keywords, ${topKeywords.length} top-level keywords)`,
);
