/**
 * Bundle GitLab CI templates into a TypeScript module.
 * Run before build: generates src/data/templates.ts
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const TEMPLATES_DIR = join(import.meta.dirname, '..', 'src', 'data', 'templates');
const OUTPUT = join(import.meta.dirname, '..', 'src', 'data', 'bundled-templates.ts');

function collectFiles(dir: string, base: string): Record<string, string> {
  const result: Record<string, string> = {};

  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = relative(base, full);

    if (statSync(full).isDirectory()) {
      Object.assign(result, collectFiles(full, base));
    } else if (entry.endsWith('.yml') || entry.endsWith('.yaml')) {
      result[rel] = readFileSync(full, 'utf-8');
    }
  }

  return result;
}

const templates = collectFiles(TEMPLATES_DIR, TEMPLATES_DIR);
const entries = Object.entries(templates)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([path, content]) => `  ${JSON.stringify(path)}: ${JSON.stringify(content)}`)
  .join(',\n');

const output = `// Auto-generated by scripts/bundle-templates.ts — do not edit
export const BUNDLED_TEMPLATES: Record<string, string> = {
${entries}
};
`;

writeFileSync(OUTPUT, output);
console.log(`Bundled ${Object.keys(templates).length} templates → ${OUTPUT}`);
